### ISSUE TITLE
(wofi:3121): Gtk-CRITICAL **: 09:54:19.447: gtk_widget_set_size_request: assertion 'height >= -1' failed

### ISSUE THREAD

**Issue by alexlnkp** [szaffarano/wofi-power-menu#18]
Error mentioned above appears during the launch of the wofi-power-menu
Packages versions (synced by the package manager):
```
wofi 1.4.1-1
dbus-glib 0.112-3
glib 1.2.10-18
glib2 2.80.0-2
glibc 2.39-1
gtk 1.2.10-18
```

OS: `Arch Linux x86_64`
Kernel: `6.8.4-arch1-1`
DE: `Hyprland`

EDIT: it seems like changing wofi height through the config toml file by appending wofi arguments with `-H 900` also doesn't work, possibly due to the error

**Comment by szaffarano** [comment]
Hi,
as you said, this error is related to the wofi height configuration.
You can reproduce it without using this tool:

```sh
# no error output
printf "A\nB\nC" | wofi -d menu --columns=1

# prints the errors with any value for --lines
printf "A\nB\nC" | wofi -d menu --columns=1 --lines=10
```
But this seems not to affect how the menu is rendered, so I guess you can ignore it and eventually report it to the [wofi developer](https://sr.ht/~scoopta/wofi/)
