### ISSUE TITLE
Feature Request: customize commands that are executed by each option

### ISSUE THREAD

**Issue by alexlnkp** [szaffarano/wofi-power-menu#20]
As it is now, the commands are hard-coded to do exactly the same thing for every user, every DE, etc
The issue is that on my specific DE (Hyprland) commands for logging out like `loginctl terminate-session` basically throw me out back to my tty, which is a bit unfortunate.
Hyprland has its own way of terminating a session, using the `hyprctl dispatch exit` command. Just so this issue doesn't happen to anyone else, i think it's best if the commands that are executed for each option in the power-menu can be customized via the config file.

Wish i could help to be entirely honest, but i'm more of a C++ guy :/

**Comment by szaffarano** [comment]
Hi @alexlnkp 
If I understood you correctly, the feature is already implemented: you have a `cmd` attribute to override the command, e.g.

```toml
[menu.logout]
  cmd = "hyprctl dispatch exit"
```

Please let me know whether it works for your use case.

**Comment by alexlnkp** [comment]
> Hi @alexlnkp If I understood you correctly, the feature is already implemented: you have a `cmd` attribute to override the command, e.g.
> 
> ```toml
> [menu.logout]
>   cmd = "hyprctl dispatch exit"
> ```
> 
> Please let me know whether it works for your use case.

Well, it does work!

The new issue i noticed is that some buttons change their identity if other one is disabled
I'll open the new issue right now
