### ISSUE TITLE
Info for suggested font 

### ISSUE THREAD

**Issue by smartshogu** [szaffarano/wofi-power-menu#33]
Hello szaffarano,

I'm currently using wofi-power-menu on Swaywm on Debian 12 and I've encountered a small issue. I need to know which font I should install to display the icons correctly. At the moment i use 
```
# Default Font
font pango:Terminus 12
```
and I get tofu in the menu.

Thanks in advance!

**Comment by szaffarano** [comment]
Hi @smartshogu 

I use `FiraCode Nerd Font`. 

Please feel free to reopen the issue if you need further help
