### ISSUE TITLE
Error when icon is empty

### ISSUE THREAD

**Issue by smartshogu** [szaffarano/wofi-power-menu#34]
Hello szaffarano, i found a small problem 

part of my config-file looks like this:

```
[menu.logout]
  #icon = ""
  icon = ""
  cmd = "swaymsg exit"
```

with `icon = ""` wofi-power-menu wont run an reports in terminal: `Error: failed to get stdin`. 
Funny thing is, when `cmd = ""` it **will run** and do nothing. So maybe wofi-power-menu should run even if `icon = ""`.

**Comment by szaffarano** [comment]
Hi @smartshogu 
I've just created [a pr](https://github.com/szaffarano/wofi-power-menu/pull/39) fixing it.

Thanks for pointing it out!

**Comment by szaffarano** [comment]
Fix published: https://github.com/szaffarano/wofi-power-menu/releases/tag/v0.2.3
